// <auto-generated />
using System;
using AiManagementApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AiManagementApp.Migrations
{
    [DbContext(typeof(AiManagementAppDb))]
    [Migration("20251114234013_UpdateTableName")]
    partial class UpdateTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiManagementApp.Models.AiLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("DHRequisicao")
                        .HasColumnType("DATE")
                        .HasColumnName("data_hora_requisicao");

                    b.Property<int>("Nivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nivel");

                    b.Property<string>("RecomendacaoGerada")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("recomendacao_gerada");

                    b.Property<string>("ResumoRecebido")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("resumo_recebido");

                    b.Property<string>("SucessoEnvio")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("sucesso_envio");

                    b.HasKey("Id");

                    b.ToTable("TBL_AI_LOGS");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3bdc1f2-8c32-4a1a-9e71-8f2f3d16a101"),
                            DHRequisicao = new DateTime(2025, 11, 7, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Nivel = 1,
                            RecomendacaoGerada = "Percebo que você está carregando muita coisa ao mesmo tempo. Experimente fazer uma pausa curta, respirar fundo por alguns instantes e organizar suas prioridades com calma. Pequenos intervalos podem aliviar bastante a pressão.",
                            ResumoRecebido = "Usuário relatou excesso de carga emocional no trabalho.",
                            SucessoEnvio = "Y"
                        },
                        new
                        {
                            Id = new Guid("f41e7692-57d7-4384-9bc8-1165c6d3f0e2"),
                            DHRequisicao = new DateTime(2025, 11, 8, 10, 32, 0, 0, DateTimeKind.Unspecified),
                            Nivel = 0,
                            RecomendacaoGerada = "Seu corpo pode estar pedindo um descanso mais estruturado. Tente evitar telas alguns minutos antes de dormir e procure desacelerar o ritmo gradualmente. Pequenos ajustes na rotina noturna podem ajudar bastante.",
                            ResumoRecebido = "Usuário descreveu dificuldade para dormir.",
                            SucessoEnvio = "Y"
                        },
                        new
                        {
                            Id = new Guid("3e1acf1d-7827-4c4c-b7c7-bc1bb909a2e9"),
                            DHRequisicao = new DateTime(2025, 11, 9, 11, 23, 0, 0, DateTimeKind.Unspecified),
                            Nivel = 1,
                            RecomendacaoGerada = "É totalmente compreensível se sentir irritado em dias mais tensos. Se puder, tire um momento para respirar profundamente e se afastar um pouco da situação. Às vezes, alguns segundos de calma já ajudam a clarear a cabeça.",
                            ResumoRecebido = "Usuário relatou irritabilidade com colegas.",
                            SucessoEnvio = "Y"
                        },
                        new
                        {
                            Id = new Guid("2c5e62e7-0265-4a12-a184-55c5c8eb44c7"),
                            DHRequisicao = new DateTime(2025, 11, 10, 11, 46, 0, 0, DateTimeKind.Unspecified),
                            Nivel = 0,
                            RecomendacaoGerada = "É normal ter dias em que a motivação demora a aparecer. Que tal começar com uma tarefa bem simples? Cumprir um pequeno passo pode ajudar a criar um ritmo melhor para o restante do dia.",
                            ResumoRecebido = "Usuário relatou sensação de desmotivação pela manhã.",
                            SucessoEnvio = "Y"
                        },
                        new
                        {
                            Id = new Guid("d2c17420-9f84-4ee4-8c20-102875f79d0b"),
                            DHRequisicao = new DateTime(2025, 11, 11, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Nivel = 1,
                            RecomendacaoGerada = "Reuniões intensas podem realmente deixar o corpo e a mente sobrecarregados. Tente alongar os ombros e o pescoço por alguns segundos e respirar lentamente. Isso pode ajudar a liberar parte dessa tensão.",
                            ResumoRecebido = "Usuário relatou tensão acumulada após uma reunião difícil.",
                            SucessoEnvio = "Y"
                        },
                        new
                        {
                            Id = new Guid("e4a7f0fa-3e44-4fd1-a92d-cdc7284a88bb"),
                            DHRequisicao = new DateTime(2025, 11, 12, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Nivel = 0,
                            RecomendacaoGerada = "Tudo bem ter uma manhã mais devagar. Você pode tentar dividir suas próximas tarefas em passos menores — isso ajuda a reconstruir o ritmo sem se sentir pressionado. Vá no seu tempo.",
                            ResumoRecebido = "Usuário relatou desmotivação leve após manhã improdutiva.",
                            SucessoEnvio = "Y"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
